# Generated by Django 5.2.6 on 2026-01-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, upload_to='', verbose_name='makaleyefotografekleyin'),
        ),
    ]
