# Generated by Django 6.0.5 on 2026-05-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-comment_date"]},
        ),
        migrations.AlterField(
            model_name="article",
            name="article_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles/",
                verbose_name="Makaleye fotoğraf ekleyin",
            ),
        ),
    ]
